import Head from 'next/head';
import { useTranslation, Trans } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

// Delete the following line if you are using Emotion
import styles from '../styles/Home.module.css';

const Home = () => {
  const { t } = useTranslation('common');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Production App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          <Trans i18nKey="home.welcome">
            Welcome to production-grade <a href="https://nextjs.org">Next.js</a>{' '}
            starter kit!
          </Trans>
        </h1>

        <p>
          <Trans i18nKey="home.start">
            Get started by editing <code>pages/index.js</code>
          </Trans>
        </p>
      </main>

      <footer className={styles.footer}>{t('footer')}</footer>
    </div>
  );
};

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}

export default Home;
